package com.example.data

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "media_tracks")
data class MediaTrack(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    var title: String,
    var artist: String,
    var album: String,
    var genre: String,
    val filePath: String, // local path, content URI, or web demo stream URL
    val isVideo: Boolean,
    val duration: Long, // milliseconds
    val sampleRate: String = "44.1 kHz", // for high quality lossless audio tagging
    val bitRate: String = "320 kbps",    // bit depth or bitrate
    val format: String, // e.g. MP3, FLAC, WAV, ALAC, MP4
    var lyricsLrc: String? = null, // Synchronized Lyrics in LRC format (e.g. "[00:12.30]Hello")
    val isDownloaded: Boolean = false,
    val sourceUrl: String? = null, // Original URL if downloaded offline
    var imageUrl: String? = null, // Custom image/artwork URL or path
    var isFavorite: Boolean = false, // Starred favorite track
    val dateAdded: Long = System.currentTimeMillis()
)

@Entity(tableName = "playlists")
data class Playlist(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    val isAutoGenerated: Boolean = false,
    val targetGenre: String? = null
)

@Entity(tableName = "playlist_tracks", primaryKeys = ["playlistId", "trackId"])
data class PlaylistTrack(
    val playlistId: Long,
    val trackId: Long
)

@Entity(tableName = "equalizer_presets")
data class EqualizerPreset(
    @PrimaryKey val name: String, // "Normal", "Klasik", "Pop", "Rock", "Custom"
    val band60Hz: Float = 0f,   // dB index (usually -15f to +15f)
    val band230Hz: Float = 0f,
    val band910Hz: Float = 0f,
    val band4kHz: Float = 0f,
    val band14kHz: Float = 0f
)
